Personal_Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

# Se hace lo de app_name por si tenemos alguna vista similar en diferentes apps
# Django sepa a cual acceder mediante al app_name
# en la template debe queda asi:  <a href="{% url 'blog:blog' blog.id %}"><h3>{{ blog.title }}</h3></a>
app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name="blog_home"),
    path('<int:blog_id>/', views.blog, name="blog")
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.home, name="home"),
]

blog/models.py
from django.db import models

# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)
    image = models.ImageField(upload_to="blog/media", blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    date = models.DateField()

    # Return el nombre en los elementos creados dentro del admin.
    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    image = models.ImageField(
        upload_to='portfolio/media', blank=True, null=True)
    url = models.URLField(blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, name="Fecha de Creacion")

    # Return el nombre en los elementos creados dentro del admin.
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
# Create your views here.


def blog_home(request):
    blogs = Blog.objects.order_by('-date')
    return render(request, 'blog/allblogs.html', {'blogs': blogs})


def blog(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/blog.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
# Importando el modelo Projects para mapearlo en la vista principal del portafolio
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/allblogs.html
{% extends "portfolio/base.html" %}

{% block title %}
Rachid's Blogs
{% endblock %}

{% block content %}
<center><h2>{{ blogs.count }} blog{{ blogs.count|pluralize }}</h2><center>
<br>
{% for blog in blogs %}
    {% if blog.image %}
        <center><img src="{{ blog.image.url }}" width="400" height="250" class="rounded mx-auto d-block"/></center>
    {% endif %}
    <a href="{% url 'blog:blog' blog.id %}"><h3>{{ blog.title }}</h3></a>
    <center><p>{{ blog.date|date:'M d Y'}}</p></center>
    <p>{{ blog.description|striptags|truncatechars:100 }}</p>
{% endfor %}
{% endblock %}

blog/templates/blog/blog.html
{% extends "portfolio/base.html" %}

{% block title %}
{{ blog.title }}
{% endblock %}

{% block content %}
{% if blog.url %}
    <center><h1>{{ blog.title }}</h1></center>
    <br>
    {% if blog.image %}
        <center><a href="{{ blog.url }}"><img src="{{ blog.image.url }}" width="400" height="250" class="rounded mx-auto d-block"/></a><center>
    {% endif %}
    <center><h2>--{{ blog.date|date:'F jS Y' }}--</h2></center>    
    <br>
    <br>
    <center><p>{{ blog.description }}</p><center>
{% else %}
    <center><h1>{{ blog.title }}</h1></center>
    <br>
    {% if blog.image %}
        <center><img src="{{ blog.image.url }}" width="400" height="250" class="rounded mx-auto d-block"/><center>
    {% endif %}
    <center><h2>--{{ blog.date|date:'F jS Y' }}--</h2></center>
    <br>
    <br>
    <center><p>{{ blog.description }}</p><center>
{% endif %}
{% endblock %}

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'portfolio/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">Rachid's PortFolio</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'blog:blog_home' %}">Blog</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">RACHID MOYSE POLANIA</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">Pentester, Developer, Latin Lover</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
                    </div>
                </div>
            </div>
        </header>

{% block content %}{% endblock %}

        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Rachid Moyse Polania</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'portfolio/js/scripts.js' %}"></script>
    </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}


{% block title %}
Rachid's Portfolio
{% endblock %}

{% block content %}
<section class="page-section" id="services">
            <div class="container">
                <h2 class="text-center mt-0">At Your Service</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-gem text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Pentesting</h3>
                            <p class="text-muted mb-0">Penetration testing to physical infrastructure and cloud.</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Development</h3>
                            <p class="text-muted mb-0">FullStack websites with Django and boostrap!</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Networking</h3>
                            <p class="text-muted mb-0">Cisco equipment configuration!</p>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-heart text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Cloud Architect</h3>
                            <p class="text-muted mb-0">creation of cloud solutions and security in these!</p>
                        </div>
                    </div>
                </div>
            </div>
</section>
{% for project in projects %}
<div id="portfolio">
    <div class="container-fluid p-0">
        <div class="row no-gutters">
            <div class="col-lg-4 col-sm-6">
                <a class="portfolio-box" href="{{ project.image.url }}">
                    <img class="img-fluid" src="{{ project.image.url }}" width="400" height="250" alt="" />
                    <div class="portfolio-box-caption">
                        <div class="project-category text-white-50">{{ project.title }}</div>
                        <div class="project-name">{{ project.description }}</div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<br>
{% endfor %}
<br>
<br>
<section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">Let's Get In Touch!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">Ready to start your next project with me? Give me a call or send us an email and we will get back to you as soon as possible!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>+57 (314) 435-1189</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block" href="mailto:rachidmoyse1@hotmail.com">rachidmoyse1@hotmail.com</a>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}